"""race img

Revision ID: bdc068e7f469
Revises: d49db257bb55
Create Date: 2024-08-11 15:15:27.731818

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bdc068e7f469"
down_revision: Union[str, None] = "d49db257bb55"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("races", sa.Column("img_url", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("races", "img_url")
    # ### end Alembic commands ###
